# Name and version of this dbt project.
name: 'templateone_cases_eventlog'
version: '1.0.0'
require-dbt-version: [">=1.0.0", "<2.0.0"]
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'templateone_cases_eventlog'

vars:
   # Name of the schema where the raw input data is stored.
  schema_sources: "templateone_cases_eventlog"

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

# Directory which will store compiled SQL files and will be removed by 'dbt clean'.
target-path: "target"
clean-targets:
  - "target"

# All models are materialized as tables by default.
models:
  +materialized: table

# Quoting is enabled for databases, schemas, and identifiers.
quoting:
  database: true
  schema: true
  identifier: true

# Quoting is enabled for columns in the seeds files.
seeds:
  quote_columns: true 
