# Copy this content for the setup
templateone_cases_eventlog:
  outputs:

    sqlserver:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server:
      port: 1433
      user:
      password:
      database:
      schema:

  target: sqlserver